version: '3.7'

services:
  bborm:
    build: .
    image: bahadirbirsoz/bb_orm:latest
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - network

  mysql:
    image: mysql:5.7.20
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - network

volumes:
  mysql:

networks:
  network:
